### ISSUE TITLE
A Player position would be appreciated.

### ISSUE THREAD

**Issue by Texlo-Dev** [lavalibs/lavalink.js#15]
**Is your feature request related to a problem? Please describe.**
I find myself needing to figure out how much time a song has left. However, there is no Player state or time that they player has left which you can use to help determine this.

**Describe the solution you'd like**
Add a <Player>.position number which represents how much time is left for the player.

**Describe alternatives you've considered**
No alternatives

**Additional context**

**Comment by appellation** [comment]
Player position is sent with the `playerUpdate` event, which is emitted on both the player and the node. You can implement this yourself quite easily.

```js
node.on('playerUpdate', ({ guildId, { state: { position } } }) => node.players.get(guildId).position = position);
```

This library makes a point of keep local state to a minimum, and omitting state such as position is a design choice. I'm happy to discuss this with users, but right now we keep state limited to what the library needs internally or what cannot be determined otherwise from lavalink itself (e.g. the player's playing status).

**Comment by RTK99** [comment]
Thanks.
Maybe this should be documented on your doc page. I can see a lot of people needing this.
